// src/lib/schema/index.ts
import * as authSchema from "../../auth-schema"; // generated by Better Auth CLI
import { tasks, events, shoppingList, userGroups, userGroupMembers, userGroupRequests } from "./server/db/schema";   // your own app tables

export const schema = {
  ...authSchema,
  // App-specific tables
  tasks,
  events,
  shoppingList,
  userGroups,
  userGroupMembers,
  userGroupRequests
};
